names:
  0: person
  1: bicycle
  2: car
  3: motorcycle
  4: bus
  5: truck
  6: rider
path: C:\Users\prabh\Downloads\thermal-border-intrusion\thermal-border-intrusion\data\processed
test: test/images
train: train/images
val: val/images
